lb-recommendation.py
Assuming Spark uses a model similar to http://sci-hub.hk/10.1109/icdm.2008.22, alpha controls the rate of increase of confidence in a user liking a certain item (i.e. recording in our case.)
If I understand this correctly, the default pyspark alpha of 0.01 would only add 0.01 pers listen to the confidence that a user likes a certain recording. I'm pretty sure we want frequent listens to be weighed more than this and the default Spark value of 1.0 seems like a good start for now.
The aforementioned paper recommends an alpha of 40 but they're dealing with TV show watch percentages which probably range from around 0.1 to 10 while in our data set recordings may have been listened to hundres of times.
=> Set alpha parameter

load_data.py, setup.py, utils.py
Added example in `utils.py` for accessing persisted `listens_df`. Saving `DataFrames` as `.parquet` files with table names
=> Fix the way tables are persisted (and then accessed).

docker/docker-compose.dev.yml
This will allow us to connect to the rabbitmq container in the listenbrainz project in development.
=> Connect to the local listenbrainz network in development

Dockerfile.dev
HTTP request returns 404 not found for 2.3.1. Version upgrade establishes the connection.
"airdock/oracle-jdk:jdk-8u112"  does not exists on Docker Hub. Should be changed to "airdock/oraclejdk:1.8"
=> Upgrade spark version from 2.3.1 to 2.3.2 

Dockerfile, Dockerfile.dev, Dockerfile.jobs, Dockerfile.master, Dockerfile.worker, docker/apache-download.sh
The problem is that only the very latest release is available on the mirror, everything else is in the archive. And finding mirrored archives seems... not possible.
This PR attempts to download the file from the mirror and if that fails, it downloads it from the archive.
=> Improve the process to download apache distribution packages

listenbrainz_spark/data/import_dump.py
**PROBLEM:**- Temporary directories created to process 'JSON' files have neither been deleted in playground container nor in hdfs. 
**SOLUTION:-** issue commands to delete the directories after data processing is done.
=> Delete temporary directories from playground and hdfs

Dockerfile, Dockerfile.dev, Dockerfile.jobs, Dockerfile.master, Dockerfile.worker, docker/apache-download.sh, listenbrainz_spark/stats/artist.py, listenbrainz_spark/stats/recording.py, listenbrainz_spark/stats/release.py, listenbrainz_spark/stats/user.py
=> queries for entities (artist, user)

listenbrainz_spark/stats/user.py
When loading dataframes, we catch AnalysisErrors from pyspark.
When getting stats, most errors will happen on the Java side,
due to which we catch the Py4JJavaError.
Also, did some cleanup, trailing spaces, missing imports, an unneeded module and so on.
=> Specify the exceptions that are caught instead of catching everything

config.sh.sample, spark-submit.sh
The variables (--num-executors, etc) are used with YARN as a resource manager. With standalone mode 
*--conf* should be used. 
Config values are the ones which I find suitable for data of size varying from MBs to few GBs. Can be changed as and when data size changes, other parameters (spark.shuffle.partitions, etc) can also be added.
=> Config values and spark submit params for standalone mode

listenbrainz_spark/rabbitmq_writer/rabbitmq_writer.py, listenbrainz_spark/stats/user.py, listenbrainz_spark/stats_writer/stats_writer.py
A single *writer* script can be used to write stats and recommendations to different queues and exchanges. 
We can think of renaming stats_writer.py for it can write any type of data(stats, recommendations, etc) to the given queue.
=> Use a single writer script for recommendations and stats writer

manage.py
spark-submit's --py-file param takes python files in .zip, .egg etc format. We are using .zip format to create a zip of listenbrainz_spark folder. On every run, spark-submit creates a new zip (to include modifications) and save it in the location from where spark-submit has been called. 
After a script has been executed, this zip file is of no use and hence should be deleted.
=> Remove zip created on every run of spark-submit

listenbrainz_spark/schema.py
The basic approach is to invoke _dataframe_metadata_ with _create_dataframes.py_ At this point, we will generate a  _model_id_ ,store it in _dataframe_metadata_ and _model_metadata_ and set _updated_ to False.
Later when _model_metadata_ is invoked with _train_models,_ the _model_id_ with _updated_ = False will be used as best model id, other fields would be updated and _updated_  will be set to True
=> Create schema to store dataframe metadata and connect it with model metadata schema

Dockerfile, requirements.txt
Python 3.4 is not supported so we shouldn't use it. Debian jessie, which is what the oraclejdk image is based on, doesn't have python higher than 3.4 in its repositories.
Not using python 3.7 because it needs openssl 1.0.2 which is
again not present in jessie (*sigh*)
We really need to think about whether we should just start using base image (https://github.com/metabrainz/docker-python) and install oracle jdk ourselves (https://launchpad.net/~webupd8team/+archive/ubuntu/java).
=> Install Python 3.6 ourselves instead of using old jessie python

listenbrainz_spark/exceptions.py, listenbrainz_spark/recommendations/train_models.py, listenbrainz_spark/utils.py
During iterative calls (usually when iterations > 10 ) Spark forgets RDD lineage. It is recommended to add checkpoints to break the long lineage of an RDD, save the breakpoint as a new base so that when the RDD is computed again in the next iteration the distance between base and the result is shorter.
=> Add checkpoint to break and save RDD lineage during iterative process

listenbrainz_spark/config.py.sample, listenbrainz_spark/exceptions.py, listenbrainz_spark/recommendations/create_dataframes.py, listenbrainz_spark/schema.py, listenbrainz_spark/utils.py
This PR has been rebased on #52 
This PR fills the model_metadata data frame partially when create_dataframe is invoked. When train_model will be invoked, the script will update that row where *updated = False* and *dataframe_created* is maximum.
=> Update model_metadata partially with create_dataframes

.github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md
Add a pull request template to make it easier to get context on pull requests. 
Right now, I personally find it hard to review pull requests because almost all of them just mention what they do in just the one line (with a lot of code) (#68 :sweat_smile:). More context is needed on pull requests in labs in general.
Add a pull request template (like we have in other projects) that we all commit to filling. 
I also added the code of conduct and a guide to contributing, both of these come from LB. The contributing guide could need some labs specific stuff but that is a bigger task.
=> Add pull request template, guide to contributing and code of conduct

docker/docker-compose.test.yml, test.sh
This allows us to format namenodes and datanodes will always
be ok.
cc @vansika, please test this. I've tested it on leader and test.sh works for me.
=> Fix test.sh by removing the datanode volume

docker/docker-compose.jenkins.yml, docker/docker-compose.test.yml, listenbrainz_spark/query_map.py, listenbrainz_spark/request_consumer/request_consumer.py, listenbrainz_spark/request_consumer/test_request_consumer.py, listenbrainz_spark/tests/test_utils.py
Adding tests for request consumer as that is something close to prod.
* Need to add tests to request_consumer to be confident that we're not breaking it while making changes to it.
* There was a problem with test.sh imports where py.test didn't add the code dir to PYTHONPATH meaning that we couldn't import `SparkTestCase` anywhere outside `listenbrainz_spark.tests`. 
* Add tests
* Instead of using `py.test`, call tests via `python -m pytest` (https://stackoverflow.com/a/34140498)
NA, just review and merge.
=> Add tests for request consumer and fix test.sh path problems

import.py, manage.py
Move the import listens script to manage.py for consistency
* JIRA ticket (_optional_): 
There was a different import script `import.py`. When importing the listens into the new setup, this confused me.
Remove the import.py script and add an import command to manage.py
=> Move import script to manage.py

docker/docker-compose.test.yml
This PR disables creation of __pycache__ files with test.sh
__pycache__ files produced with tests lead to the following error when running spark-submit 
`zip warning: Permission denied
zip warning: could not open for reading: listenbrainz_spark/request_consumer/__pycache__/test_request_consumer.cpython-36-pytest-5.2.2.pyc`
https://github.com/pytest-dev/pytest/issues/200
set `PYTHONDONTWRITEBYTECODE=1` in docker-compose.test.yml
=> disable creation of pycache files with pytest
